# Daily Repository Automation Script
# Purpose: Automate maintenance and improvements across all Purmamarca repositories
# Run this daily via Task Scheduler or manually

param(
    [string]$WorkspaceRoot = "C:\Users\roanc\.gemini\antigravity\scratch",
    [switch]$DryRun = $false
)

$ErrorActionPreference = "Continue"
$Date = Get-Date -Format "yyyy-MM-dd"
$ReportPath = "$WorkspaceRoot\automation_reports"

# Create reports directory
if (-not (Test-Path $ReportPath)) {
    New-Item -ItemType Directory -Path $ReportPath | Out-Null
}

$ReportFile = "$ReportPath\report_$Date.md"

# Initialize report
$Report = @"
# Daily Automation Report - $Date

## 🤖 Automation Summary

**Execution Time:** $(Get-Date -Format "HH:mm:ss")
**Mode:** $(if ($DryRun) { "DRY RUN" } else { "LIVE" })

---

## 📦 Repository Status

"@

# Define repositories to manage
$Repositories = @(
    @{Name="dropship-blueprint"; Path="$WorkspaceRoot\dropship-blueprint"; Remote="https://github.com/Purmamarca/dropship-blueprint-dashboard"},
    @{Name="eco-site-arg"; Path="$WorkspaceRoot\eco-site-arg"; Remote="https://github.com/Purmamarca/eco-site-arg"}
)

$TotalCommits = 0
$TotalChanges = 0
$Issues = @()

foreach ($repo in $Repositories) {
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host "  Processing: $($repo.Name)" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    
    $Report += "`n### $($repo.Name)`n"
    
    if (-not (Test-Path $repo.Path)) {
        $Report += "- ⚠️ **Status:** Repository not found locally`n"
        $Issues += "Repository $($repo.Name) not found at $($repo.Path)"
        continue
    }
    
    Set-Location $repo.Path
    
    # Pull latest changes
    Write-Host "Pulling latest changes..." -ForegroundColor Yellow
    $pullResult = git pull origin main 2>&1
    
    if ($pullResult -match "Already up to date") {
        $Report += "- ✅ **Pull:** Already up to date`n"
    } else {
        $Report += "- 🔄 **Pull:** Updates received`n"
    }
    
    # Check status
    $status = git status --porcelain
    
    if ([string]::IsNullOrWhiteSpace($status)) {
        $Report += "- ✅ **Status:** Clean working directory`n"
    } else {
        $changeCount = ($status -split "`n").Count
        $TotalChanges += $changeCount
        $Report += "- 📝 **Status:** $changeCount uncommitted changes`n"
    }
    
    # Get last commit
    $lastCommit = git log -1 --pretty=format:"%s" 2>&1
    $Report += "- 📌 **Last Commit:** $lastCommit`n"
    
    # Check for common issues
    Write-Host "Checking for issues..." -ForegroundColor Yellow
    
    # Check for large files
    $largeFiles = Get-ChildItem -Path $repo.Path -Recurse -File | Where-Object { $_.Length -gt 10MB }
    if ($largeFiles) {
        $Report += "- ⚠️ **Warning:** Found $($largeFiles.Count) files larger than 10MB`n"
        $Issues += "Large files in $($repo.Name): $($largeFiles.Name -join ', ')"
    }
    
    # Check for missing README
    if (-not (Test-Path "$($repo.Path)\README.md")) {
        $Report += "- ⚠️ **Warning:** Missing README.md`n"
        $Issues += "Missing README in $($repo.Name)"
    } else {
        $Report += "- ✅ **Documentation:** README.md present`n"
    }
    
    # Check for LICENSE
    if (-not (Test-Path "$($repo.Path)\LICENSE")) {
        $Report += "- ⚠️ **Warning:** Missing LICENSE file`n"
        $Issues += "Missing LICENSE in $($repo.Name)"
    } else {
        $Report += "- ✅ **Legal:** LICENSE file present`n"
    }
}

# Add improvements section
$Report += @"

---

## 🔧 Automated Improvements

"@

# Check if any improvements were made
if ($TotalChanges -eq 0) {
    $Report += "- No automated improvements needed today`n"
} else {
    $Report += "- Found $TotalChanges potential improvements`n"
}

# Add issues section
$Report += @"

---

## ⚠️ Issues Detected

"@

if ($Issues.Count -eq 0) {
    $Report += "- ✅ No issues detected`n"
} else {
    foreach ($issue in $Issues) {
        $Report += "- ⚠️ $issue`n"
    }
}

# Add metrics
$Report += @"

---

## 📊 Metrics

- **Repositories Processed:** $($Repositories.Count)
- **Total Changes Detected:** $TotalChanges
- **Issues Flagged:** $($Issues.Count)
- **Execution Time:** $(Get-Date -Format "HH:mm:ss")

---

## 🎯 Next Steps

"@

if ($Issues.Count -gt 0) {
    $Report += "1. Review and resolve flagged issues`n"
    $Report += "2. Run automation again to verify fixes`n"
} else {
    $Report += "1. All repositories are healthy`n"
    $Report += "2. Continue with regular development`n"
}

$Report += @"

---

**Generated by:** Daily Automation Script
**Date:** $Date
"@

# Save report
$Report | Out-File -FilePath $ReportFile -Encoding UTF8

Write-Host "`n========================================" -ForegroundColor Green
Write-Host "  ✅ AUTOMATION COMPLETE" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "`nReport saved to: $ReportFile" -ForegroundColor Cyan
Write-Host "`nSummary:" -ForegroundColor Yellow
Write-Host "  - Repositories: $($Repositories.Count)" -ForegroundColor White
Write-Host "  - Changes: $TotalChanges" -ForegroundColor White
Write-Host "  - Issues: $($Issues.Count)" -ForegroundColor White

# Return to original location
Set-Location $WorkspaceRoot

# Open report
if (-not $DryRun) {
    Start-Process $ReportFile
}
